feat: converted top-level files in src/controllers to TS good first i…
nkowaokwu/igbo_api pull request #680
Opened 2023-06-21 13:09 UTC by Stancobridge

## Describe your changes
This PR converts the top-levels files in `src/controllers` folder from JS to TS. I also noticed some implementations that needs modifications and tried my best to update the implementations. I also added some comments to help check some implementations if they are required

## Issue ticket number and link
Closed #672 

## How Has This Been Tested?
I ran the test with `sudo yarn test`, I used sudo because my terminal is not permitted to create the `db` folder and it returned the response below

## Screenshots (if appropriate):
![igbo api test](https://github.com/nkowaokwu/igbo_api/assets/22870440/e3a2e4ed-4892-4893-ade6-1a0148004d80)

2023-07-01 13:44 UTC, ijemmao commented
@Stancobridge are you still working on this PR?

2023-07-01 13:52 UTC, Stancobridge commented
> @Stancobridge are you still working on this PR?

Nope am done

2023-07-04 02:51 UTC, ijemmao commented
@Stancobridge please address the failing CI build - I'm not able to merge your work until it passes all green
![image](https://github.com/nkowaokwu/igbo_api/assets/16169291/8455199b-b837-4887-a7bc-a9a0617db12e)

It seems like two tests are failing

## Error log
<img width="966" alt="Screen Shot 2023-07-03 at 10 51 18 PM" src="https://github.com/nkowaokwu/igbo_api/assets/16169291/b92f4bf3-6cb9-4356-a73b-35206ec3d3f9">

2023-07-04 03:03 UTC, ijemmao requested changes
i appreciate this PR! but i think it's grown a bit out of scope since you've introduced your own changes after converting these files to TS and adding types

i know there's parts of the code that can be written better, but converting to TS and making changes to improve code readability (that's doesn't relate to TS, i.e. `await` vs. `.then`) makes it more challenging for me to see what changes were made only for converting from JS to TS

since i had to leave a lot of comments, I recommend starting fresh - that way you don't possibly miss a file where you didn't revert your changes

the added benefit of starting fresh is that the two failing tests will stop failing!

2023-07-04 03:03 UTC, ijemmao commented on src/controllers/utils/index.ts
> +  const hasQuotes = keywordQuery && keywordQuery.match(/["'].*["']/) !== null;
revert this change

2023-07-04 03:03 UTC, ijemmao commented on src/controllers/words.ts
> +
revert this change

2023-07-04 03:03 UTC, ijemmao commented on src/controllers/words.ts
> +
revert this change

2023-07-04 03:03 UTC, ijemmao commented on src/controllers/words.ts
> +
revert this change

2023-07-04 03:03 UTC, ijemmao commented on src/controllers/words.ts
> +
revert this change

2023-07-04 03:03 UTC, ijemmao commented on src/controllers/words.ts
> +  (newWord as any).examples = exampleIds;
we don't want to use `any` please use `unknown` if you're unable to use a more specific type

2023-07-04 05:52 UTC, Stancobridge commented
Alright doing that

2023-07-05 13:50 UTC, ijemmao commented
alright @Stancobridge i'm closing this PR so you can start a fresh one!

2023-07-05 13:50 UTC, closed without merging